from pydantic import BaseModel
class DesktopHostSummaryV500Alpha46(BaseModel):
    ready: bool = True
    phase: str = "v5_0_alpha_46_desktop_foundation_package_a"
    scope: str = "desktop_host_core"
    desktop_host: bool = True
    desktop_bootstrap: bool = True
    window_manager: bool = True
    navigation_shell: bool = True
    theme_manager: bool = True
    config_loader: bool = True
    desktop_session: bool = True
    desktop_health: bool = True
    exe_packaging_enabled: bool = False
    commercial_execution_engine_enabled: bool = False
    commercial_api_key_required: bool = False
    real_execution_enabled: bool = False
    real_broker_connection_enabled: bool = False
    backward_compatible: bool = True
    test_pack_size: int = 80
