from fastapi import APIRouter
from app.v500_alpha36_plugin_versioning.service import PluginVersioningFacadeV500Alpha36

router = APIRouter(prefix="/v5-0-alpha-36/plugin-versioning", tags=["v5.0-alpha.36-plugin-versioning"])
_service = PluginVersioningFacadeV500Alpha36()

@router.get("/summary")
async def summary(): return _service.summary()
@router.get("/parse")
async def parse(): return _service.parse()
@router.get("/compare")
async def compare(): return _service.compare()
@router.get("/compatibility-matrix")
async def compatibility_matrix(): return _service.compatibility_matrix()
@router.get("/supported")
async def supported(): return _service.supported()
@router.get("/dependencies")
async def dependencies(): return _service.dependencies()
@router.get("/dependency-graph")
async def dependency_graph(): return _service.dependency_graph()
@router.get("/upgrade-plan")
async def upgrade_plan(): return _service.upgrade_plan()
@router.get("/marketplace")
async def marketplace(): return _service.marketplace()
@router.get("/report")
async def report(): return _service.report()
@router.get("/readiness")
async def readiness(): return _service.readiness()
@router.get("/contract")
async def contract(): return _service.contract()
