from fastapi import APIRouter
from app.v500_alpha50_packaging_enablement.service import guarded_packaging_enablement_facade_v500_alpha50 as _service
router=APIRouter(prefix='/v5-0-alpha-50/packaging-enablement',tags=['v5.0-alpha.50-packaging-enablement'])
@router.get('/summary')
async def summary(): return _service.summary()
@router.get('/execute-guard')
async def execute_guard(): return _service.execute_guard()
@router.get('/dependency-check')
async def dependency_check(): return _service.dependency_check()
@router.get('/pyinstaller-check')
async def pyinstaller_check(): return _service.pyinstaller_check()
@router.get('/real-build-gate')
async def real_build_gate(): return _service.real_build_gate()
@router.get('/artifact-hash-plan')
async def artifact_hash_plan(): return _service.artifact_hash_plan()
@router.get('/report')
async def report(): return _service.report()
@router.get('/readiness')
async def readiness(): return _service.readiness()
@router.get('/contract')
async def contract(): return _service.contract()
