from fastapi import APIRouter
from app.v500_alpha48_windows_builder.service import windows_executable_builder_facade_v500_alpha48 as _service
router = APIRouter(prefix="/v5-0-alpha-48/windows-builder", tags=["v5.0-alpha.48-windows-builder"])
@router.get("/summary")
async def summary(): return _service.summary()
@router.get("/coordinator")
async def coordinator(): return _service.coordinator()
@router.get("/exe-contract")
async def exe_contract(): return _service.exe_contract()
@router.get("/portable")
async def portable(): return _service.portable()
@router.get("/installer")
async def installer(): return _service.installer()
@router.get("/resources")
async def resources(): return _service.resources()
@router.get("/output")
async def output(): return _service.output()
@router.get("/startup")
async def startup(): return _service.startup()
@router.get("/dependencies")
async def dependencies(): return _service.dependencies()
@router.get("/smoke-test")
async def smoke_test(): return _service.smoke_test()
@router.get("/dashboard")
async def dashboard(): return _service.dashboard()
@router.get("/report")
async def report(): return _service.report()
@router.get("/readiness")
async def readiness(): return _service.readiness()
@router.get("/contract")
async def contract(): return _service.contract()
