from fastapi import APIRouter
from app.v500_alpha50_artifact_registration.service import local_exe_artifact_registration_facade_v500_alpha50 as _service
router=APIRouter(prefix='/v5-0-alpha-50/artifact-registration',tags=['v5.0-alpha.50-artifact-registration'])
@router.get('/summary')
async def summary(): return _service.summary()
@router.get('/exe-detector')
async def exe_detector(): return _service.exe_detector()
@router.get('/hash-generator')
async def hash_generator(): return _service.hash_generator()
@router.get('/portable-zip')
async def portable_zip(): return _service.portable_zip()
@router.get('/registry-update')
async def registry_update(): return _service.registry_update()
@router.get('/build-result')
async def build_result(): return _service.build_result()
@router.get('/smoke-result')
async def smoke_result(): return _service.smoke_result()
@router.get('/report')
async def report(): return _service.report()
@router.get('/readiness')
async def readiness(): return _service.readiness()
@router.get('/contract')
async def contract(): return _service.contract()
