from fastapi import APIRouter
from app.v500_alpha25_self_healing_patch_pipeline.service import SelfHealingPatchPipelineFacadeV500Alpha25
router = APIRouter(prefix="/v5-0-alpha-25/self-healing-patch", tags=["v5.0-alpha.25-self-healing-patch"])
_service = SelfHealingPatchPipelineFacadeV500Alpha25()
@router.get("/summary")
async def summary(): return _service.summary()
@router.get("/discover")
async def discover(): return _service.discover()
@router.get("/parse")
async def parse(script_name: str = "apply_v5_0_alpha_24_runtime_api_smoke_patch.py"): return _service.parse(script_name)
@router.get("/dry-run")
async def dry_run(): return _service.dry_run()
@router.get("/manifest")
async def manifest(): return _service.manifest()
@router.get("/manifest-update-contract")
async def manifest_update_contract(): return _service.manifest_update_contract()
@router.get("/smoke")
async def smoke(): return _service.smoke()
@router.get("/verify-sample")
async def verify_sample(): return _service.verify_sample()
@router.get("/readiness")
async def readiness(): return _service.readiness()
@router.get("/contract")
async def contract(): return _service.contract()
