from fastapi import APIRouter
from app.v500_alpha38_exchange_connectivity.service import exchange_connectivity_facade_v500_alpha38 as _service

router = APIRouter(prefix="/v5-0-alpha-38/exchange-connectivity", tags=["v5.0-alpha.38-exchange-connectivity"])

@router.get("/summary")
async def summary(): return _service.summary()
@router.get("/session")
async def session(): return _service.session()
@router.get("/close-session")
async def close_session(): return _service.close_session()
@router.get("/connection-state")
async def connection_state(): return _service.connection_state()
@router.get("/heartbeat")
async def heartbeat(): return _service.heartbeat()
@router.get("/timeout-check")
async def timeout_check(): return _service.timeout_check()
@router.get("/latency")
async def latency(): return _service.latency()
@router.get("/latency-grade")
async def latency_grade(): return _service.latency_grade()
@router.get("/stream-contract")
async def stream_contract(): return _service.stream_contract()
@router.get("/subscribe-preview")
async def subscribe_preview(): return _service.subscribe_preview()
@router.get("/websocket-event")
async def websocket_event(): return _service.websocket_event()
@router.get("/report")
async def report(): return _service.report()
@router.get("/readiness")
async def readiness(): return _service.readiness()
@router.get("/contract")
async def contract(): return _service.contract()
