from fastapi import APIRouter
from app.v500_alpha40_ai_agent_runtime.service import ai_agent_runtime_facade_v500_alpha40 as _service

router = APIRouter(prefix="/v5-0-alpha-40/ai-agent-runtime", tags=["v5.0-alpha.40-ai-agent-runtime"])

@router.get("/summary")
async def summary(): return _service.summary()
@router.get("/decision-graph")
async def decision_graph(): return _service.decision_graph()
@router.get("/graph-validation")
async def graph_validation(): return _service.graph_validation()
@router.get("/agents")
async def agents(): return _service.agents()
@router.get("/runtime-contract")
async def runtime_contract(): return _service.runtime_contract()
@router.get("/dry-run")
async def dry_run(): return _service.dry_run()
@router.get("/reasoning-trace")
async def reasoning_trace(): return _service.reasoning_trace()
@router.get("/decision-policy")
async def decision_policy(): return _service.decision_policy()
@router.get("/runtime-safety")
async def runtime_safety(): return _service.runtime_safety()
@router.get("/report")
async def report(): return _service.report()
@router.get("/readiness")
async def readiness(): return _service.readiness()
@router.get("/contract")
async def contract(): return _service.contract()
