from fastapi import APIRouter
from app.v500_alpha41_strategy_simulation.service import strategy_simulation_facade_v500_alpha41 as _service
router = APIRouter(prefix='/v5-0-alpha-41/strategy-simulation', tags=['v5.0-alpha.41-strategy-simulation'])
@router.get('/summary')
async def summary(): return _service.summary()
@router.get('/backtest-contract')
async def backtest_contract(): return _service.backtest_contract()
@router.get('/simulate')
async def simulate(): return _service.simulate()
@router.get('/scenarios')
async def scenarios(): return _service.scenarios()
@router.get('/metrics')
async def metrics(): return _service.metrics()
@router.get('/replay')
async def replay(): return _service.replay()
@router.get('/safety')
async def safety(): return _service.safety()
@router.get('/report')
async def report(): return _service.report()
@router.get('/readiness')
async def readiness(): return _service.readiness()
@router.get('/contract')
async def contract(): return _service.contract()
