from fastapi import APIRouter
from app.v500_alpha33_ai_decision_integration.service import AIDecisionIntegrationFacadeV500Alpha33
router = APIRouter(prefix="/v5-0-alpha-33/ai-decision-integration", tags=["v5.0-alpha.33-ai-decision-integration"])
_service = AIDecisionIntegrationFacadeV500Alpha33()
@router.get("/summary")
async def summary(): return _service.summary()
@router.get("/context")
async def context(): return _service.context()
@router.get("/evidence")
async def evidence(): return _service.evidence()
@router.get("/decision")
async def decision(): return _service.decision()
@router.get("/event-bus")
async def event_bus(): return _service.event_bus()
@router.get("/logging")
async def logging(): return _service.logging()
@router.get("/alert")
async def alert(): return _service.alert()
@router.get("/status")
async def status(): return _service.status()
@router.get("/readiness")
async def readiness(): return _service.readiness()
@router.get("/contract")
async def contract(): return _service.contract()
