from fastapi import APIRouter
from app.v500_alpha33_ai_decision_enterprise.service import AIDecisionEnterpriseFacadeV500Alpha33
router = APIRouter(prefix="/v5-0-alpha-33/ai-decision-enterprise", tags=["v5.0-alpha.33-ai-decision-enterprise"])
_service = AIDecisionEnterpriseFacadeV500Alpha33()
@router.get("/summary")
async def summary(): return _service.summary()
@router.get("/security")
async def security(): return _service.security()
@router.get("/performance")
async def performance(): return _service.performance()
@router.get("/quality-score")
async def quality_score(): return _service.quality_score()
@router.get("/runtime-acceptance")
async def runtime_acceptance(): return _service.runtime_acceptance()
@router.get("/sprint-report")
async def sprint_report(): return _service.sprint_report()
@router.get("/final-status")
async def final_status(): return _service.final_status()
@router.get("/readiness")
async def readiness(): return _service.readiness()
@router.get("/contract")
async def contract(): return _service.contract()
