from fastapi import APIRouter
from app.v500_alpha41_strategy_core.service import strategy_core_facade_v500_alpha41 as _service

router = APIRouter(prefix="/v5-0-alpha-41/strategy-core", tags=["v5.0-alpha.41-strategy-core"])

@router.get("/summary")
async def summary(): return _service.summary()
@router.get("/strategies")
async def strategies(): return _service.strategies()
@router.get("/strategy-contract")
async def strategy_contract(): return _service.strategy_contract()
@router.get("/dry-run")
async def dry_run(): return _service.dry_run()
@router.get("/signal")
async def signal(): return _service.signal()
@router.get("/rules")
async def rules(): return _service.rules()
@router.get("/safety")
async def safety(): return _service.safety()
@router.get("/report")
async def report(): return _service.report()
@router.get("/readiness")
async def readiness(): return _service.readiness()
@router.get("/contract")
async def contract(): return _service.contract()
