from fastapi import APIRouter
from app.v500_alpha29_backtest_engine.service import BacktestEngineFacadeV500Alpha29
router = APIRouter(prefix="/v5-0-alpha-29/backtest-engine", tags=["v5.0-alpha.29-backtest-engine"])
_service = BacktestEngineFacadeV500Alpha29()
@router.get("/summary")
async def summary(): return _service.summary()
@router.get("/config")
async def config(): return _service.config()
@router.get("/dataset")
async def dataset(): return _service.dataset()
@router.get("/signals")
async def signals(): return _service.signals()
@router.get("/trades")
async def trades(): return _service.trades()
@router.get("/report")
async def report(): return _service.report()
@router.get("/run")
async def run(): return _service.run()
@router.get("/readiness")
async def readiness(): return _service.readiness()
@router.get("/contract")
async def contract(): return _service.contract()
