from fastapi import APIRouter
from app.v500_alpha46_desktop_dashboard_intelligence.service import desktop_dashboard_intelligence_facade_v500_alpha46 as _service

router = APIRouter(prefix="/v5-0-alpha-46/desktop-dashboard-intelligence", tags=["v5.0-alpha.46-desktop-dashboard-intelligence"])

@router.get("/summary")
async def summary(): return _service.summary()
@router.get("/dashboard")
async def dashboard(): return _service.dashboard()
@router.get("/widgets")
async def widgets(): return _service.widgets()
@router.get("/plugin-loader")
async def plugin_loader(): return _service.plugin_loader()
@router.get("/progress")
async def progress(): return _service.progress()
@router.get("/sprint")
async def sprint(): return _service.sprint()
@router.get("/modules")
async def modules(): return _service.modules()
@router.get("/tests")
async def tests(): return _service.tests()
@router.get("/build")
async def build(): return _service.build()
@router.get("/health")
async def health(): return _service.health()
@router.get("/report")
async def report(): return _service.report()
@router.get("/readiness")
async def readiness(): return _service.readiness()
@router.get("/contract")
async def contract(): return _service.contract()
