from fastapi import APIRouter
from app.v500_alpha49_desktop_gui.service import desktop_dashboard_gui_shell_facade_v500_alpha49 as _service

router = APIRouter(prefix="/v5-0-alpha-49/desktop-gui", tags=["v5.0-alpha.49-desktop-gui"])

@router.get("/summary")
async def summary(): return _service.summary()
@router.get("/shell")
async def shell(): return _service.shell()
@router.get("/navigation")
async def navigation(): return _service.navigation()
@router.get("/status-bar")
async def status_bar(): return _service.status_bar()
@router.get("/runtime-panel")
async def runtime_panel(): return _service.runtime_panel()
@router.get("/build-panel")
async def build_panel(): return _service.build_panel()
@router.get("/ci-panel")
async def ci_panel(): return _service.ci_panel()
@router.get("/health-panel")
async def health_panel(): return _service.health_panel()
@router.get("/ui-state")
async def ui_state(): return _service.ui_state()
@router.get("/report")
async def report(): return _service.report()
@router.get("/readiness")
async def readiness(): return _service.readiness()
@router.get("/contract")
async def contract(): return _service.contract()
