from fastapi import APIRouter
from app.v500_alpha43_broker_order.service import broker_order_facade_v500_alpha43 as _service
router = APIRouter(prefix="/v5-0-alpha-43/broker-order", tags=["v5.0-alpha.43-broker-order"])
@router.get("/summary")
async def summary(): return _service.summary()
@router.get("/adapter-contract")
async def adapter_contract(): return _service.adapter_contract()
@router.get("/order-mapping")
async def order_mapping(): return _service.order_mapping()
@router.get("/dry-route")
async def dry_route(): return _service.dry_route()
@router.get("/paper-order")
async def paper_order(): return _service.paper_order()
@router.get("/dry-submit")
async def dry_submit(): return _service.dry_submit()
@router.get("/safety")
async def safety(): return _service.safety()
@router.get("/report")
async def report(): return _service.report()
@router.get("/readiness")
async def readiness(): return _service.readiness()
@router.get("/contract")
async def contract(): return _service.contract()
