from fastapi import APIRouter
from app.v500_alpha35_portfolio_analytics_risk.service import PortfolioAnalyticsRiskFacadeV500Alpha35

router = APIRouter(prefix="/v5-0-alpha-35/portfolio-analytics-risk", tags=["v5.0-alpha.35-portfolio-analytics-risk"])
_service = PortfolioAnalyticsRiskFacadeV500Alpha35()

@router.get("/summary")
async def summary(): return _service.summary()
@router.get("/equity-curve")
async def equity_curve(): return _service.equity_curve()
@router.get("/analytics")
async def analytics(): return _service.analytics()
@router.get("/returns")
async def returns(): return _service.returns()
@router.get("/drawdown")
async def drawdown(): return _service.drawdown()
@router.get("/volatility")
async def volatility(): return _service.volatility()
@router.get("/concentration")
async def concentration(): return _service.concentration()
@router.get("/capital-allocation")
async def capital_allocation(): return _service.capital_allocation()
@router.get("/risk-score")
async def risk_score(): return _service.risk_score()
@router.get("/report")
async def report(): return _service.report()
@router.get("/readiness")
async def readiness(): return _service.readiness()
@router.get("/contract")
async def contract(): return _service.contract()
