from fastapi import APIRouter
from app.v500_alpha23_risk_engine.service import RiskEngineFacadeV500Alpha23
router = APIRouter(prefix="/v5-0-alpha-23/risk-engine", tags=["v5.0-alpha.23-risk-engine"])
_service = RiskEngineFacadeV500Alpha23()
@router.get("/summary")
async def summary(): return _service.summary()
@router.get("/policy")
async def policy(): return _service.policy()
@router.get("/position-size")
async def position_size(): return _service.position_size()
@router.get("/daily-loss")
async def daily_loss(): return _service.daily_loss()
@router.get("/drawdown")
async def drawdown(): return _service.drawdown()
@router.get("/exposure")
async def exposure(): return _service.exposure()
@router.get("/preflight")
async def preflight(): return _service.preflight()
@router.get("/blocked-preflight")
async def blocked_preflight(): return _service.blocked_preflight()
@router.get("/readiness")
async def readiness(): return _service.readiness()
@router.get("/contract")
async def contract(): return _service.contract()
