from fastapi import APIRouter
from app.v500_alpha38_exchange_core.service import exchange_core_facade_v500_alpha38 as _service
router = APIRouter(prefix="/v5-0-alpha-38/exchange-core", tags=["v5.0-alpha.38-exchange-core"])
@router.get("/summary")
async def summary(): return _service.summary()
@router.get("/contract")
async def contract(): return _service.contract()
@router.get("/exchanges")
async def exchanges(): return _service.exchanges()
@router.get("/default-exchange")
async def default_exchange(): return _service.default_exchange()
@router.get("/capabilities")
async def capabilities(): return _service.capabilities()
@router.get("/market-types")
async def market_types(): return _service.market_types()
@router.get("/health")
async def health(): return _service.health()
@router.get("/safety")
async def safety(): return _service.safety()
@router.get("/status")
async def status(): return _service.status()
@router.get("/readiness")
async def readiness(): return _service.readiness()
