from fastapi import APIRouter
from app.v500_alpha22_broker_layer.service import BrokerLayerFacadeV500Alpha22
router = APIRouter(prefix="/v5-0-alpha-22/broker-layer", tags=["v5.0-alpha.22-broker-layer"])
_service = BrokerLayerFacadeV500Alpha22()
@router.get("/summary")
async def summary(): return _service.summary()
@router.get("/capabilities")
async def capabilities(): return _service.capabilities()
@router.get("/safety-policy")
async def safety_policy(): return _service.safety_policy()
@router.get("/preflight-order")
async def preflight_order(): return _service.preflight_order()
@router.get("/submit-order-contract")
async def submit_order_contract(): return _service.submit_order_contract()
@router.get("/sample-position")
async def sample_position(): return _service.sample_position()
@router.get("/sample-wallet")
async def sample_wallet(): return _service.sample_wallet()
@router.get("/readiness")
async def readiness(): return _service.readiness()
@router.get("/contract")
async def contract(): return _service.contract()
