from fastapi import APIRouter
from app.v500_alpha46_desktop_host.service import desktop_host_facade_v500_alpha46 as _service
router = APIRouter(prefix="/v5-0-alpha-46/desktop-host", tags=["v5.0-alpha.46-desktop-host"])
@router.get("/summary")
async def summary(): return _service.summary()
@router.get("/host")
async def host(): return _service.host()
@router.get("/bootstrap")
async def bootstrap(): return _service.bootstrap()
@router.get("/window")
async def window(): return _service.window()
@router.get("/navigation")
async def navigation(): return _service.navigation()
@router.get("/theme")
async def theme(): return _service.theme()
@router.get("/config")
async def config(): return _service.config()
@router.get("/session")
async def session(): return _service.session()
@router.get("/health")
async def health(): return _service.health()
@router.get("/report")
async def report(): return _service.report()
@router.get("/readiness")
async def readiness(): return _service.readiness()
@router.get("/contract")
async def contract(): return _service.contract()
