from fastapi import APIRouter
from app.v500_alpha48_windows_app.service import windows_app_bootstrap_facade_v500_alpha48 as _service

router = APIRouter(prefix="/v5-0-alpha-48/windows-app", tags=["v5.0-alpha.48-windows-app"])

@router.get("/summary")
async def summary(): return _service.summary()
@router.get("/bootstrap")
async def bootstrap(): return _service.bootstrap()
@router.get("/runtime-shell")
async def runtime_shell(): return _service.runtime_shell()
@router.get("/main-window")
async def main_window(): return _service.main_window()
@router.get("/startup-flow")
async def startup_flow(): return _service.startup_flow()
@router.get("/local-backend")
async def local_backend(): return _service.local_backend()
@router.get("/dashboard-host")
async def dashboard_host(): return _service.dashboard_host()
@router.get("/health")
async def health(): return _service.health()
@router.get("/exe-handoff")
async def exe_handoff(): return _service.exe_handoff()
@router.get("/report")
async def report(): return _service.report()
@router.get("/readiness")
async def readiness(): return _service.readiness()
@router.get("/contract")
async def contract(): return _service.contract()
