from app.v52_alpha_legacy_marker_launcher_sync_diagnostics.models import LegacyMarkerLauncherSyncDiagnosticsSummaryV52Alpha

def test_guard(): assert LegacyMarkerLauncherSyncDiagnosticsSummaryV52Alpha().auto_trading_enabled is False
