from app.v500_alpha39_live_data_enterprise.models import LiveDataEnterpriseSummaryV500Alpha39

def test_v500_alpha39_e_summary_conn(): assert LiveDataEnterpriseSummaryV500Alpha39().real_connection is False
