from app.v500_alpha43_broker_account.models import BrokerAccountSummaryV500Alpha43

def test_v500_alpha43_b_summary_account(): assert BrokerAccountSummaryV500Alpha43().real_account_read_enabled is False
