from app.v500_alpha50_artifact_registration.service import LocalExeArtifactRegistrationFacadeV500Alpha50

def test_no_final_exe(): assert LocalExeArtifactRegistrationFacadeV500Alpha50().summary().final_exe_generated is False
