from app.v500_alpha41_strategy_simulation.models import StrategySimulationSummaryV500Alpha41

def test_v500_alpha41_d_summary_broker(): assert StrategySimulationSummaryV500Alpha41().broker_connection_enabled is False
