from app.v500_alpha41_strategy_enterprise.models import StrategyEnterpriseSummaryV500Alpha41

def test_v500_alpha41_e_summary_broker(): assert StrategyEnterpriseSummaryV500Alpha41().broker_connection_enabled is False
