from app.v500_alpha49_desktop_finalization.service import InternalDesktopBuildFinalizationFacadeV500Alpha49

def test_facade_smoke_finalization():
 assert InternalDesktopBuildFinalizationFacadeV500Alpha49().smoke_finalization() is not None
