from app.v500_alpha35_portfolio_ai_optimization.models import PortfolioAIOptimizationSummaryV500Alpha35

def test_v500_alpha35_c_summary_backcompat(): assert PortfolioAIOptimizationSummaryV500Alpha35().backward_compatible is True
