from app.v500_alpha37_broker_connectivity.models import BrokerConnectivitySummaryV500Alpha37

def test_v500_alpha37_c_summary_backcompat(): assert BrokerConnectivitySummaryV500Alpha37().backward_compatible is True
