from app.v500_alpha42_execution_analytics.models import ExecutionAnalyticsSummaryV500Alpha42

def test_v500_alpha42_d_summary_exec(): assert ExecutionAnalyticsSummaryV500Alpha42().real_execution_enabled is False
