from app.v500_alpha36_plugin_runtime_sandbox.models import PluginRuntimeSandboxSummaryV500Alpha36

def test_v500_alpha36_b_summary_exec(): assert PluginRuntimeSandboxSummaryV500Alpha36().real_execution_enabled is False
