from app.v500_alpha39_live_stream_manager.models import LiveStreamManagerSummaryV500Alpha39

def test_v500_alpha39_c_summary_conn(): assert LiveStreamManagerSummaryV500Alpha39().real_connection is False
