from app.v500_alpha41_strategy_allocation.models import StrategyAllocationSummaryV500Alpha41

def test_v500_alpha41_c_summary_exec(): assert StrategyAllocationSummaryV500Alpha41().real_execution_enabled is False
