from app.v500_alpha38_exchange_market_data.models import ExchangeMarketDataSummaryV500Alpha38

def test_v500_alpha38_b_summary_auto(): assert ExchangeMarketDataSummaryV500Alpha38().auto_trading_enabled is False
