from app.v500_alpha42_execution_enterprise.models import ExecutionEnterpriseSummaryV500Alpha42

def test_v500_alpha42_e_summary_auto(): assert ExecutionEnterpriseSummaryV500Alpha42().auto_trading_enabled is False
