from app.v500_alpha39_live_data_enterprise.models import LiveDataEnterpriseSummaryV500Alpha39

def test_v500_alpha39_e_summary_auto(): assert LiveDataEnterpriseSummaryV500Alpha39().auto_trading_enabled is False
