from app.v500_alpha41_strategy_scoring.models import StrategyScoringSummaryV500Alpha41

def test_v500_alpha41_b_summary_exec(): assert StrategyScoringSummaryV500Alpha41().real_execution_enabled is False
