from app.v500_alpha36_plugin_runtime_sandbox.models import PluginRuntimeSandboxSummaryV500Alpha36

def test_v500_alpha36_b_count_guard(): assert PluginRuntimeSandboxSummaryV500Alpha36().ready is True
