from app.v500_alpha49_desktop_finalization.service import InternalDesktopBuildFinalizationFacadeV500Alpha49

def test_facade_portable_readiness():
 assert InternalDesktopBuildFinalizationFacadeV500Alpha49().portable_readiness() is not None
