from app.v500_alpha41_strategy_enterprise.models import StrategyEnterpriseSummaryV500Alpha41

def test_v500_alpha41_e_summary_auto(): assert StrategyEnterpriseSummaryV500Alpha41().auto_trading_enabled is False
