from app.v500_alpha49_desktop_finalization.service import InternalDesktopBuildFinalizationFacadeV500Alpha49

def test_commercial_no_execution(): assert InternalDesktopBuildFinalizationFacadeV500Alpha49().report()['commercial_execution_engine_enabled'] is False
