from app.v500_alpha50_release_candidate.service import InternalRCPreparationFacadeV500Alpha50

def test_auto_trading_default_off(): assert InternalRCPreparationFacadeV500Alpha50().summary().auto_trading_default is False
