from app.v500_alpha37_broker_orders_account.models import BrokerOrdersAccountSummaryV500Alpha37

def test_v500_alpha37_b_summary_auto(): assert BrokerOrdersAccountSummaryV500Alpha37().auto_trading_enabled is False
