from app.v500_alpha42_execution_core.models import ExecutionCoreSummaryV500Alpha42

def test_v500_alpha42_a_summary_broker(): assert ExecutionCoreSummaryV500Alpha42().broker_connection_enabled is False
