from app.v500_alpha38_exchange_connectivity.models import ExchangeConnectivitySummaryV500Alpha38

def test_v500_alpha38_c_summary_auto(): assert ExchangeConnectivitySummaryV500Alpha38().auto_trading_enabled is False
