from app.v500_alpha49_desktop_finalization.service import InternalDesktopBuildFinalizationFacadeV500Alpha49

def test_no_final_exe(): assert InternalDesktopBuildFinalizationFacadeV500Alpha49().summary().final_exe_generated is False
