from app.v500_alpha38_exchange_connectivity.models import ExchangeConnectivitySummaryV500Alpha38

def test_v500_alpha38_c_summary_backcompat(): assert ExchangeConnectivitySummaryV500Alpha38().backward_compatible is True
