from app.v500_alpha43_broker_monitoring.models import BrokerMonitoringSummaryV500Alpha43

def test_v500_alpha43_d_summary_auto(): assert BrokerMonitoringSummaryV500Alpha43().auto_trading_enabled is False
