from app.v500_alpha37_broker_connectivity.models import BrokerConnectivitySummaryV500Alpha37

def test_v500_alpha37_c_summary_exec(): assert BrokerConnectivitySummaryV500Alpha37().real_execution_enabled is False
