from app.v500_alpha43_broker_monitoring.models import BrokerMonitoringSummaryV500Alpha43

def test_v500_alpha43_d_summary_account(): assert BrokerMonitoringSummaryV500Alpha43().real_account_read_enabled is False
