from app.v500_alpha39_live_data_enterprise.models import LiveDataEnterpriseSummaryV500Alpha39

def test_v500_alpha39_e_summary_ws(): assert LiveDataEnterpriseSummaryV500Alpha39().real_websocket is False
