from app.v500_alpha37_broker_enterprise.models import BrokerEnterpriseSummaryV500Alpha37

def test_v500_alpha37_d_summary_auto(): assert BrokerEnterpriseSummaryV500Alpha37().auto_trading_enabled is False
