from fastapi import APIRouter
from app.v500_alpha47_build_pipeline.service import build_pipeline_facade_v500_alpha47 as _service

router = APIRouter(prefix="/v5-0-alpha-47/build-pipeline", tags=["v5.0-alpha.47-build-pipeline"])

@router.get("/summary")
async def summary(): return _service.summary()
@router.get("/core")
async def core(): return _service.core()
@router.get("/manifest")
async def manifest(): return _service.manifest()
@router.get("/metadata")
async def metadata(): return _service.metadata()
@router.get("/artifacts")
async def artifacts(): return _service.artifacts()
@router.get("/profiles")
async def profiles(): return _service.profiles()
@router.get("/config")
async def config(): return _service.config()
@router.get("/validation")
async def validation(): return _service.validation()
@router.get("/integrity")
async def integrity(): return _service.integrity()
@router.get("/hash")
async def hash_info(): return _service.hash()
@router.get("/fingerprint")
async def fingerprint(): return _service.fingerprint()
@router.get("/plugin-contract")
async def plugin_contract(): return _service.plugin_contract()
@router.get("/dashboard")
async def dashboard(): return _service.dashboard()
@router.get("/report")
async def report(): return _service.report()
@router.get("/readiness")
async def readiness(): return _service.readiness()
@router.get("/contract")
async def contract(): return _service.contract()
