from fastapi import APIRouter
from app.v500_alpha28_alert_engine.service import AlertEngineFacadeV500Alpha28
router = APIRouter(prefix="/v5-0-alpha-28/alert-engine", tags=["v5.0-alpha.28-alert-engine"])
_service = AlertEngineFacadeV500Alpha28()
@router.get("/summary")
async def summary(): return _service.summary()
@router.get("/rules")
async def rules(): return _service.rules()
@router.get("/severity")
async def severity(): return _service.severity()
@router.get("/channels")
async def channels(): return _service.channels()
@router.get("/scanner-alert")
async def scanner_alert(): return _service.scanner_alert()
@router.get("/risk-alert")
async def risk_alert(): return _service.risk_alert()
@router.get("/notify-contract")
async def notify_contract(): return _service.notify_contract()
@router.get("/status")
async def status(): return _service.status()
@router.get("/readiness")
async def readiness(): return _service.readiness()
@router.get("/contract")
async def contract(): return _service.contract()
