from fastapi import APIRouter
from app.v500_alpha39_live_data_cache.service import live_data_cache_facade_v500_alpha39 as _service

router = APIRouter(prefix="/v5-0-alpha-39/live-data-cache", tags=["v5.0-alpha.39-live-data-cache"])

@router.get("/summary")
async def summary(): return _service.summary()
@router.get("/put")
async def put(): return _service.put()
@router.get("/get")
async def get(): return _service.get()
@router.get("/history")
async def history(): return _service.history()
@router.get("/latest")
async def latest(): return _service.latest()
@router.get("/ttl-policy")
async def ttl_policy(): return _service.ttl_policy()
@router.get("/stale-check")
async def stale_check(): return _service.stale_check()
@router.get("/version")
async def version(): return _service.version()
@router.get("/warmup")
async def warmup(): return _service.warmup()
@router.get("/metrics")
async def metrics(): return _service.metrics()
@router.get("/report")
async def report(): return _service.report()
@router.get("/readiness")
async def readiness(): return _service.readiness()
@router.get("/contract")
async def contract(): return _service.contract()
