from fastapi import APIRouter
from app.v500_alpha44_live_dashboard.service import live_dashboard_facade_v500_alpha44 as _service
router = APIRouter(prefix="/v5-0-alpha-44/live-dashboard", tags=["v5.0-alpha.44-live-dashboard"])
@router.get("/summary")
async def summary(): return _service.summary()
@router.get("/data")
async def data(): return _service.data()
@router.get("/progress")
async def progress(): return _service.progress()
@router.get("/platform-progress")
async def platform_progress(): return _service.platform_progress()
@router.get("/tests")
async def tests(): return _service.tests()
@router.get("/modules")
async def modules(): return _service.modules()
@router.get("/sprint")
async def sprint(): return _service.sprint()
@router.get("/health")
async def health(): return _service.health()
@router.get("/report")
async def report(): return _service.report()
@router.get("/readiness")
async def readiness(): return _service.readiness()
@router.get("/contract")
async def contract(): return _service.contract()
