from fastapi import APIRouter
from app.v500_alpha44_pic_core.service import pic_core_facade_v500_alpha44 as _service
router = APIRouter(prefix="/v5-0-alpha-44/pic-core", tags=["v5.0-alpha.44-pic-core"])
@router.get("/summary")
async def summary(): return _service.summary()
@router.get("/project-state")
async def project_state(): return _service.project_state()
@router.get("/sprint-state")
async def sprint_state(): return _service.sprint_state()
@router.get("/version-state")
async def version_state(): return _service.version_state()
@router.get("/build-state")
async def build_state(): return _service.build_state()
@router.get("/test-state")
async def test_state(): return _service.test_state()
@router.get("/module-state")
async def module_state(): return _service.module_state()
@router.get("/health-state")
async def health_state(): return _service.health_state()
@router.get("/report")
async def report(): return _service.report()
@router.get("/readiness")
async def readiness(): return _service.readiness()
@router.get("/contract")
async def contract(): return _service.contract()
