from fastapi import APIRouter
from app.v500_alpha35_portfolio_intelligence_core.service import PortfolioIntelligenceCoreFacadeV500Alpha35

router = APIRouter(prefix="/v5-0-alpha-35/portfolio-intelligence-core", tags=["v5.0-alpha.35-portfolio-intelligence-core"])
_service = PortfolioIntelligenceCoreFacadeV500Alpha35()

@router.get("/summary")
async def summary(): return _service.summary()
@router.get("/profile")
async def profile(): return _service.profile()
@router.get("/assets")
async def assets(): return _service.assets()
@router.get("/allocation")
async def allocation(): return _service.allocation()
@router.get("/target-allocation")
async def target_allocation(): return _service.target_allocation()
@router.get("/exposure")
async def exposure(): return _service.exposure()
@router.get("/correlation")
async def correlation(): return _service.correlation()
@router.get("/correlation-risk")
async def correlation_risk(): return _service.correlation_risk()
@router.get("/rebalance")
async def rebalance(): return _service.rebalance()
@router.get("/health")
async def health(): return _service.health()
@router.get("/status")
async def status(): return _service.status()
@router.get("/readiness")
async def readiness(): return _service.readiness()
@router.get("/contract")
async def contract(): return _service.contract()
