from fastapi import APIRouter
from app.v500_alpha30_replay_engine.service import ReplayEngineFacadeV500Alpha30
router = APIRouter(prefix="/v5-0-alpha-30/replay-engine", tags=["v5.0-alpha.30-replay-engine"])
_service = ReplayEngineFacadeV500Alpha30()
@router.get("/summary")
async def summary(): return _service.summary()
@router.get("/session")
async def session(): return _service.session()
@router.get("/timeline")
async def timeline(): return _service.timeline()
@router.get("/state")
async def state(): return _service.state()
@router.get("/step-forward")
async def step_forward(): return _service.step_forward()
@router.get("/play-contract")
async def play_contract(): return _service.play_contract()
@router.get("/speed-contract")
async def speed_contract(): return _service.speed_contract()
@router.get("/backtest-link")
async def backtest_link(): return _service.backtest_link()
@router.get("/replay-summary")
async def replay_summary(): return _service.replay_summary()
@router.get("/readiness")
async def readiness(): return _service.readiness()
@router.get("/contract")
async def contract(): return _service.contract()
