from fastapi import APIRouter
from app.v500_alpha43_broker_account.service import broker_account_facade_v500_alpha43 as _service
router = APIRouter(prefix="/v5-0-alpha-43/broker-account", tags=["v5.0-alpha.43-broker-account"])
@router.get("/summary")
async def summary(): return _service.summary()
@router.get("/account-contract")
async def account_contract(): return _service.account_contract()
@router.get("/dry-account")
async def dry_account(): return _service.dry_account()
@router.get("/balances")
async def balances(): return _service.balances()
@router.get("/positions")
async def positions(): return _service.positions()
@router.get("/capability-matrix")
async def capability_matrix(): return _service.capability_matrix()
@router.get("/safety")
async def safety(): return _service.safety()
@router.get("/report")
async def report(): return _service.report()
@router.get("/readiness")
async def readiness(): return _service.readiness()
@router.get("/contract")
async def contract(): return _service.contract()
