from fastapi import APIRouter
from app.v500_alpha26_portfolio_manager.service import PortfolioManagerFacadeV500Alpha26
router = APIRouter(prefix="/v5-0-alpha-26/portfolio-manager", tags=["v5.0-alpha.26-portfolio-manager"])
_service = PortfolioManagerFacadeV500Alpha26()
@router.get("/summary")
async def summary(): return _service.summary()
@router.get("/holdings")
async def holdings(): return _service.holdings()
@router.get("/snapshot")
async def snapshot(): return _service.snapshot()
@router.get("/allocation")
async def allocation(): return _service.allocation()
@router.get("/pnl")
async def pnl(): return _service.pnl()
@router.get("/equity-curve")
async def equity_curve(): return _service.equity_curve()
@router.get("/exposure")
async def exposure(): return _service.exposure()
@router.get("/risk-check")
async def risk_check(): return _service.risk_check()
@router.get("/readiness")
async def readiness(): return _service.readiness()
@router.get("/contract")
async def contract(): return _service.contract()
