from fastapi import APIRouter
from app.v500_alpha32_strategy_optimizer_pro.service import StrategyOptimizerProFacadeV500Alpha32
router = APIRouter(prefix="/v5-0-alpha-32/optimizer-pro", tags=["v5.0-alpha.32-optimizer-pro"])
_service = StrategyOptimizerProFacadeV500Alpha32()
@router.get("/summary")
async def summary(): return _service.summary()
@router.get("/genetic")
async def genetic(): return _service.genetic()
@router.get("/walk-forward")
async def walk_forward(): return _service.walk_forward()
@router.get("/monte-carlo")
async def monte_carlo(): return _service.monte_carlo()
@router.get("/multi-objective")
async def multi_objective(): return _service.multi_objective()
@router.get("/robustness")
async def robustness(): return _service.robustness()
@router.get("/trials")
async def trials(): return _service.trials()
@router.get("/best")
async def best(): return _service.best()
@router.get("/report")
async def report(): return _service.report()
@router.get("/run")
async def run(): return _service.run()
@router.get("/readiness")
async def readiness(): return _service.readiness()
@router.get("/contract")
async def contract(): return _service.contract()
