from fastapi import APIRouter
from app.v500_alpha51_exe_smoke_build.service import windows_exe_smoke_build_facade_v500_alpha51 as _service
router=APIRouter(prefix='/v5-0-alpha-51/exe-smoke-build',tags=['v5.0-alpha.51-exe-smoke-build'])
@router.get('/summary')
async def summary(): return _service.summary()
@router.get('/build-attempt')
async def build_attempt(): return _service.build_attempt()
@router.get('/exe-check')
async def exe_check(): return _service.exe_check()
@router.get('/launch-smoke')
async def launch_smoke(): return _service.launch_smoke()
@router.get('/diagnostics')
async def diagnostics(): return _service.diagnostics()
@router.get('/dashboard')
async def dashboard(): return _service.dashboard()
@router.get('/report')
async def report(): return _service.report()
@router.get('/readiness')
async def readiness(): return _service.readiness()
@router.get('/contract')
async def contract(): return _service.contract()
