from fastapi import APIRouter
from app.v500_alpha50_release_candidate.service import internal_rc_preparation_facade_v500_alpha50 as _service
router = APIRouter(prefix='/v5-0-alpha-50/release-candidate', tags=['v5.0-alpha.50-release-candidate'])
@router.get('/summary')
async def summary(): return _service.summary()
@router.get('/manifest')
async def manifest(): return _service.manifest()
@router.get('/manual-toggle')
async def manual_toggle(): return _service.manual_toggle()
@router.get('/dashboard-toggle')
async def dashboard_toggle(): return _service.dashboard_toggle()
@router.get('/trading-state')
async def trading_state(auto_trading_enabled: bool = False, disabled_by_safety: bool = False): return _service.trading_state(auto_trading_enabled, disabled_by_safety)
@router.get('/safety-disable')
async def safety_disable(failed_module: str = 'exchange'): return _service.safety_disable(failed_module)
@router.get('/health')
async def health(): return _service.health()
@router.get('/report')
async def report(): return _service.report()
@router.get('/readiness')
async def readiness(): return _service.readiness()
@router.get('/contract')
async def contract(): return _service.contract()
