from fastapi import APIRouter
from app.v500_alpha40_ai_memory_context.service import ai_memory_context_facade_v500_alpha40 as _service

router = APIRouter(prefix="/v5-0-alpha-40/ai-memory-context", tags=["v5.0-alpha.40-ai-memory-context"])

@router.get("/summary")
async def summary(): return _service.summary()
@router.get("/memory-store")
async def memory_store(): return _service.memory_store()
@router.get("/put-memory")
async def put_memory(): return _service.put_memory()
@router.get("/session-memory")
async def session_memory(): return _service.session_memory()
@router.get("/long-term-memory")
async def long_term_memory(): return _service.long_term_memory()
@router.get("/recall")
async def recall(): return _service.recall()
@router.get("/retrieval")
async def retrieval(): return _service.retrieval()
@router.get("/context-builder")
async def context_builder(): return _service.context_builder()
@router.get("/safety")
async def safety(): return _service.safety()
@router.get("/report")
async def report(): return _service.report()
@router.get("/readiness")
async def readiness(): return _service.readiness()
@router.get("/contract")
async def contract(): return _service.contract()
