from fastapi import APIRouter
from app.v500_alpha33_ai_decision_core.service import AIDecisionCoreFacadeV500Alpha33
router = APIRouter(prefix="/v5-0-alpha-33/ai-decision-core", tags=["v5.0-alpha.33-ai-decision-core"])
_service = AIDecisionCoreFacadeV500Alpha33()
@router.get("/summary")
async def summary(): return _service.summary()
@router.get("/context")
async def context(): return _service.context()
@router.get("/evidence")
async def evidence(): return _service.evidence()
@router.get("/confidence")
async def confidence(): return _service.confidence()
@router.get("/explanation")
async def explanation(): return _service.explanation()
@router.get("/trace")
async def trace(): return _service.trace()
@router.get("/metrics")
async def metrics(): return _service.metrics()
@router.get("/event")
async def event(): return _service.event()
@router.get("/safety")
async def safety(): return _service.safety()
@router.get("/readiness")
async def readiness(): return _service.readiness()
@router.get("/contract")
async def contract(): return _service.contract()
